### ISSUE TITLE
Get Next Issues

### ISSUE THREAD

**Issue by robweber** [pallets-eco/croniter#138]
I've been using croniter in a few projects, literally for years. Always had good luck with it until recently. I had occasion to rebuild a device and installed a bunch of Python packages from scratch, croniter included. The version I got was 5.0.1 via PyPi. Right away I noticed the `get_next` values generated by this version of croniter where not correct. Since I hadn't changed any of my code I started playing around trying to figure what had changed. 

Below are there results of my tests. I ran the same demo code from the README page on several versions of croniter in a Python virtual environment. These are all on Python 3.11.2. Ultimately what I found was that anything above version 3.0.3 does not produce correct `get_next` statements. At this point I'm wondering if there is something wrong with the library, or with my environment to get these kind of results? Any help in trying to troubleshoot this would be great. I've pinned my production version at 3.0.3 until I can sort this out. 

### Demo Code - pulled from README

```
from croniter import croniter
from datetime import datetime
base = datetime(2010, 1, 25, 4, 46)
iter = croniter('*/5 * * * *', base)  # every 5 minutes

print(iter.get_next(datetime))   # 2010-01-25 04:50:00
print(iter.get_next(datetime))   # 2010-01-25 04:55:00
print(iter.get_next(datetime))   # 2010-01-25 05:00:00
```

### Expected Output

```
2010-01-25 04:50:00
2010-01-25 04:55:00
2010-01-25 05:00:00
```

### Croniter 2.0.7

```
2010-01-25 04:50:00
2010-01-25 04:55:00
2010-01-25 05:00:00
```

### Croniter 3.0.0
```
2010-01-25 04:50:00
2010-01-25 04:55:00
2010-01-25 05:00:00
```

### Croniter 3.0.1

```
2010-01-25 04:50:00
2010-01-25 04:55:00
2010-01-25 05:00:00
```

### Croniter 3.0.2

```
2010-01-25 04:50:00
2010-01-25 04:55:00
2010-01-25 05:00:00
```

### Croniter 3.0.3

```
2010-01-25 04:50:00
2010-01-25 04:55:00
2010-01-25 05:00:00
```

### Croniter 3.0.4

```
2010-01-24 16:50:00
2010-01-24 10:55:00
2010-01-24 05:00:00
```

### Croniter 4.0.0

```
2010-01-24 16:50:00
2010-01-24 10:55:00
2010-01-24 05:00:00
```

### Croniter 5.0.1

```
2010-01-24 16:50:00
2010-01-24 10:55:00
2010-01-24 05:00:00
```

**Comment by oshmoun** [comment]
I am unable to reproduce this issue on my end. Tried with both 3.11.10 and 3.12.6

**Comment by robweber** [comment]
Well that's interesting. I'll admit it's odd but I can get this behavior consistently on my Raspberry Pi running Bookworm. Have not tried other systems since this is where I need it to run. I'll try the same version of Python on some different hardware. Please leave this open for now. Thanks for checking.

**Comment by robweber** [comment]
Ok, spent a bit more time with this. I tested 3 Raspberry Pi systems and 2 amd64 based Ubuntu installs. Just some systems I had already doing other things. For all tests I did the same thing, created a Python virtual environment, installed croniter (latest 5.0.1) and ran the above code to test scheduling. 

On the 2 Ubuntu systems the code executed and produced the correct results. On the 3 RPi systems I got the odd times indicated above. All of them produced this exact series of timestamps based on the same test script: 

```
2010-01-24 16:50:00
2010-01-24 10:55:00
2010-01-24 05:00:00
```

Really seems like this is something unique to the Raspberry Pi. Just to be as thorough as possible I did one final test. I cloned this repo and ran the test suite against each architecture. 

```
pip install -r requirements/test.txt -r requirements/tox.txt
tox --current-env -e cov
```

On the Ubuntu system all tests passed (as expected). On the Raspberry Pi it failed 100 tests and then got stuck on test_1_day_step. I let it run here for about 10 minutes and then killed it. When on ARM type systems the issue is reproduceable. Any additional tests or information you need to try and reproduce this?

**Comment by latk** [comment]
Likely somehow related to the 32-bit / year-2038 checks introduced in 17bec1df7f3d266bb72f09cafd257944eba0c8eb for https://github.com/kiorky/croniter/issues/87 in croniter 3.0.4. Many Raspberry Pi models run in 32 bit mode.

The `EPOCH` handling looks particularly sus:

https://github.com/kiorky/croniter/blob/da473d9e6dd6b8ca12a6b73715f84d155c3bd705/src/croniter/croniter.py#L78

https://github.com/kiorky/croniter/blob/da473d9e6dd6b8ca12a6b73715f84d155c3bd705/src/croniter/croniter.py#L331-L338

The two code paths don't seem to be equivalent when running in a non-UTC timezone, as the `datetime.fromtimestamp(timestamp, tz=None)` method produces a naive datetime by default:

> If optional argument *tz* is `None` or not specified, the timestamp is converted to the platform’s local date and time, and the returned `datetime` object is naive.
>
> – https://docs.python.org/3/library/datetime.html#datetime.datetime.fromtimestamp

So under 32 bit, the timestamp is interpreted in the local timezone, whereas 64 bit systems interpret it as UTC.

Then, croniter's timestamp &leftrightarrow; datetime conversion under 32 bit systems drifts by the timezone offset. @robweber's observed timestamps jump 6 hours backwards at each step:

```
2010-01-24 16:50:00
2010-01-24 10:55:00
2010-01-24 05:00:00
```

This suggests that the tests ran on a system in the UTC-06:00 timezone, e.g. the Mountain Time Zone in North America.

Such a problem is unlikely to be detected in the automated tests in the GH Actions, as servers typically run under UTC without any offset.

If my interpretation is correct, the issue can likely be fixed by setting the `EPOCH` in the UTC timezone. A longer-term fix would be to avoid naive datetimes in internal calculations, as they are very difficult to use correctly.

**Comment by kiorky** [comment]
Good catch, i wrongly assumed `fromtimestamp` was naive.

So, i fixed the calculation for `EPOCH`, and also added one relevant testcase to avoid further regressions :-).

However, I'll have to postpone release of it until DST changes are done (see `wip` branch) as this commits depends on it.
Note that all the "non naive code" is reworked and the current fix relies on the new implementation.

> A longer-term fix would be to avoid naive datetime in internal calculations, as they are very difficult to use correctly.

No, croniter internals are designed to work with naive timestamp unless you explicitly use non-naive datetime.

**Comment by robweber** [comment]
If I'm following this right (and I think I am) the `EPOCH` fix will indeed fix this. I can confirm the suspicions regarding 32 bit system and my local time zone being UTC-6:00. 

I applied the fix from the linked commit on my system and running the same tests on the RPI resulted in the correct output. All of the automated tests passed as well. I'll watch for this to be merged into the main branch. Thanks for the work on this!
