### ISSUE TITLE
Possible bug 

### ISSUE THREAD

**Issue by aemitos** [pallets-eco/croniter#64]
Hi 
This is a question for now but it might be a bug.
I use `croniter` to generate events based on a crontab expression.
For the crontab: `"0 20 * * *"` (The time here is considered localized to EST).
When executed for a start date of: `2024-03-08 03:06:28` (UTC). That was converted from `11:06 p.m. EST` and the `tzinfo` was removed.
After calling the `get_next` (whitout the `start_time`), the time stamps are converted back to `tzinfo=UTC` and then `astimezone(pytz.timezone('America/Toronto')`  returns `datetime.datetime` for the hours in the same date: 20:00, 21:00, 19:00 (these are EST)
The expected was only: 20:00
After setting the time to `2024-03-08 00:00:00` and run the same, it returns the expected value. Without additional events in the same days.
I observed the behaviour for the events generated for March 10 and 11.
Is there any special condition that opens the `get_next` to generate more than one event per day for the `"0 20 * * *"`?
Thank you!

**Comment by kiorky** [comment]
Can you please post a reproducible test case ?
Because i'm not sure your first time (`2024-03-08 03:06:28`) was localized. If i understood what you say, you just used the "system" local, so using a TZ naive datetime object.
For croniter to work with TZ calculations, input datetimes should not be TZ naive from the start.
see https://github.com/kiorky/croniter?tab=readme-ov-file#about-dst
